sudo: required

language: node_js
node_js:
  - "node"

before_install:
  - sudo apt install jq

env:
  - BUILD_VERSION="$(cat package.json | jq -r '.version')-${TRAVIS_BUILD_NUMBER}"

jobs:
  include:
    - stage: build
      before_install:
        - echo "install dependencies"
      install: npm install
      before_script:
        - echo "building package"
      script: yarn build

    - stage: deploy to S3
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: "YOUR AWS ACCESS KEY"
        secret_access_key: "YOUR AWS SECRET KEY"
        bucket: "fuse-ultron"
        region: "ap-northeast-2"
